### ISSUE TITLE
Cannot `import Cropper.CropData`

### ISSUE THREAD

**Issue by mrozbarry** [mikaxyz/elm-cropper#1]
I'm use Elm 0.18, and Elm Github Install, and I get the following error when trying to `import Cropper.Types`

```
I cannot find module 'Cropper.Types'.
Module 'Main' is trying to import it.

Potential problems could be:
  * Misspelled the module name
  * Need to add a source directory or new dependency to elm-package.json

elm-live:
  elm-make failed! You can find more info above. Keep calm and take your time
  to fix your code. We’ll try to compile it again as soon as you change a file.
```

Before trying to set up my ports to crop the image/get the dataUrl, everything was fine, I am able to `import Cropper` without any problem.

**Comment by mrozbarry** [comment]
Looks like you need to do this in your elm-package.json:

```
"exposed-modules": [
  "Cropper",
  "Cropper.Types"
]
```

**Comment by mikaxyz** [comment]
Sorry for late answer. Would have expected an email notification for issues. :)

Anyhow: I have pushed [an update (2.0.0)](http://package.elm-lang.org/packages/mikaxyz/elm-cropper/latest/Cropper) fixing this by including the types in the main module.

(Did not occur to me to test the module outside my examples folder which had access to those types.)

**Comment by mrozbarry** [comment]
I ended up rolling my own cropper, but I'm happy this got fixed.

**Comment by mikaxyz** [comment]
Good for you! :) Thanks for reporting...
